version: "3.9"

services:
  db_notifications:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5437:5432"
    networks:
      - rabbitmq_network

#  web_notifications:
#    build: .
#    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8007"
#    volumes:
#      - .:/notifications
#    ports:
#      - "8007:8007"
#    depends_on:
#      - db_notifications
#    networks:
#      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge

volumes:
  postgres_data:
